arrow-box component
watson-developer-cloud/react-components pull request #28
Opened 2016-11-15 16:25 UTC by jzhang300

* add arrow-box component

2016-11-16 17:58 UTC, kognate approved these changes

2016-11-16 17:58 UTC, kognate commented on example/src/components/ArrowBoxExamples.js
> +  onClick2() {
this is a nitpick but I think the names of these click functions should be more clear or it should be one click function.  the box1 box2 thing is also a little shakey.

2016-11-16 19:46 UTC, nfriedly commented
It looks like there's an issue with the z-index:

<img width="401" alt="screen shot 2016-11-16 at 2 45 55 pm" src="https://cloud.githubusercontent.com/assets/114976/20362989/83494d82-ac0b-11e6-996b-d02050fbc2db.png">

2016-11-16 19:54 UTC, nfriedly commented on example/src/components/ArrowBoxExamples.js
> +  onClick2() {
Yea, it feels a bit off to me. I might just suggest having complete code in the first example and omitting the second one. 

If you wanted to go even farther, you could make the example stateless:

```jsx
<div style={{ position: 'relative' }}>
  This is the element that the ArrowBox is anchored to.
  <ArrowBox
    direction="top"
    show={true}
    color={Colors.red_50}
    icon="error"
  >
    <p className="base--p" style={{ color: '#fff', textAlign: 'left' }}>
      This arrow box is now oriented to the <b>top</b>.
    </p>
  </ArrowBox>
</div>
```

2016-11-16 19:57 UTC, nfriedly requested changes
I think the z-index thing is probably a blocker, the rest is nice-to-have.

2016-11-16 19:57 UTC, nfriedly commented on example/src/components/ArrowBoxExamples.js
> +import Colors from '../../../src/components/Colors';
This should be shown in the example code (or else we should just use hex values)

2016-11-16 20:10 UTC, nfriedly commented
Given that the changes here are necessarily included in #29, I'd recommend closing this PR and just working on that one.

2016-11-16 22:59 UTC, jzhang300 commented on example/src/components/ArrowBoxExamples.js
> +  onClick2() {
Maybe the example was a little fancy :P

2016-11-17 00:01 UTC, jzhang300 commented
Closing this pr and carrying any changes to arrowbox over to #29

2016-11-17 00:01 UTC, closed without merging